version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  express:
    image: node:latest
    container_name: express
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase

  angular:
    image: node:latest
    container_name: angular
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build -- --prod"
    depends_on:
      - express

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - angular

volumes:
  mongodb_data:
